BackendBundle\Entity\Club:
    type: entity
    table: clubs
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        nacionality:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        coach:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        coachImg:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: coach_img
        logo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
    lifecycleCallbacks: {  }
