BackendBundle\Entity\Player:
    type: entity
    table: players
    indexes:
        fk_players_clubs:
            columns:
                - club_id
        fk_players_positions:
            columns:
                - position_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        number:
            type: integer
            nullable: true
            options:
                unsigned: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        nacionality:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        dateBirth:
            type: date
            nullable: true
            column: date_birth
        height:
            type: integer
            nullable: true
            options:
                unsigned: false
        weight:
            type: integer
            nullable: true
            options:
                unsigned: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        club:
            targetEntity: Club
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
        position:
            targetEntity: Position
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                position_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
